import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './globals.css'
import Card from '@/components/baro/card'
import useLenis from './useLenis'
import LenisProvider from './LenisProvider'
import FloatingCard from '@/components/baro/floating'

const spaceGrotesk = Space_Grotesk({
    variable: '--font-space-grotesk',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${spaceGrotesk.variable} bg-black`}>
                <LenisProvider>
                    <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 items-start p-4">
                        <div className="col-span-1 lg:col-span-1 md:sticky top-20">
                            <Card />
                        </div>
                        <div className="col-span-1 lg:col-span-3">
                            {children}
                        </div>
                    </div>
                    <FloatingCard />
                </LenisProvider>
            </body>
        </html>
    )
}
